namespace: ffc-ffd
namespaceTopics:
  - name: backend-poc-data
    owner: 'yes'
    roleAssignments:  
    - roleName: TopicSender
    - roleName: TopicReceiver 
    topicSubscriptions:
    - name: backend-poc-data-subscription

postgres:
  db:
    name: backend 
    charset: UTF8
    collation: en_US.utf8
