# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ffd-backend-poc:
    build:
      target: development
    image: ffc-ffd-backend-poc-development
    container_name: ffc-ffd-backend-poc-development
    ports:
      - "9228:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ffd-backend-poc-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
