environment: development
environmentCode:
name: ffc-ffd-backend-poc
namespace: fcp-ffd
workstream: fcp-ffd
image: ffc-ffd-backend-poc

labels:
  component: web

appInsights:
  connectionString:

deployment: {}

container:
  memCpuTier: M
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
